baseurl = "/"
languageCode = "en-us"
title = "Just A Data Geek"
theme = "blackburn"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/richard-ian-carpenter"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/RICarpenter"
[[menu.main]]
    name = "Links"
    url = "/links/"
[[menu.main]]
    name = "Home"
    url = "https://www.justadatageek.com/"

[params]
    description = "Exploring and analyzing data because... data!"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

